name       : flask
version    : 1.0.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/F/Flask/Flask-1.0.2.tar.gz : 2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    A microframework based on Werkzeug, Jinja2 and good intentions
builddeps  :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-pytest
    - python-setuptools
    - python-werkzeug
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
setup      : |
    rm -fr examples/flaskr/
    rm -fr examples/minitwit/
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f%}3"
    done
    %python_install
check      : |
    export LC_ALL=en_US.utf8
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test
    popd
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD py.test3 -k "not test_session_expiration and not test_no_error_swallowing"
    popd
