name       : flask
version    : 1.0.3
release    : 4
source     :
    - https://github.com/pallets/flask/archive/1.0.3.tar.gz : d42345bf227548c2eaba8661058b90c77430413d0dee5d3369c97cf67a57272b
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    A microframework based on Werkzeug, Jinja2 and good intentions
builddeps  :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-pytest
    - python-werkzeug
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
setup      : |
    rm -fr examples/flaskr/
    rm -fr examples/minitwit/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
