name       : flask
version    : 0.12.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/F/Flask/Flask-0.12.2.tar.gz : 49f44461237b69ecd901cc7ce66feea0319b9158743dd27a2899962ab214dac1
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    A microframework based on Werkzeug, Jinja2 and good intentions
builddeps  :
    - python-setuptools
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
build      : |
    %python_setup
install    : |
    %python_install
