name       : flask
version    : 1.1.2
release    : 9
source     :
    - https://github.com/pallets/flask/archive/1.1.2.tar.gz : 6da812f0fb52ad1ccfb5b3868b1dd20e420cc6e77379c2a4ecbaccd3eceb8923
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    A microframework based on Werkzeug, Jinja2 and good intentions
builddeps  :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-pytest
    - python-werkzeug
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
setup      : |
    rm -fr examples/flaskr/
    rm -fr examples/minitwit/
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3
