name       : flask
version    : 2.1.2
release    : 10
source     :
    - https://github.com/pallets/flask/archive/2.1.2.tar.gz : 7d9a32b84cd6cafa0cbd4e3bd7411cd46d3d8112b3c0fc15623cc72bacce52ee
homepage   : https://palletsprojects.com/p/flask/
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    Flask is a lightweight WSGI web application framework. It is designed to make getting started quick and easy, with the ability to scale up to complex applications. It began as a simple wrapper around Werkzeug and Jinja and has become one of the most popular Python web application frameworks.
builddeps  :
    - python-click        # check
    - python-itsdangerous # check
    - python-jinja        # check
    - python-pytest       # check
    - python-werkzeug     # check
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
setup      : |
    rm -fr examples/flaskr/
    rm -fr examples/minitwit/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
