name       : flask
version    : 1.1.1
release    : 5
source     :
    - https://github.com/pallets/flask/archive/1.1.1.tar.gz : f8f873890b75f866a190f931d426d64ac0a61a6166650c4b076815ae36bbbf61
license    : BSD-3-Clause
component  : programming.python
summary    : A microframework based on Werkzeug, Jinja2 and good intentions
description: |
    A microframework based on Werkzeug, Jinja2 and good intentions
builddeps  :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-pytest
    - python-werkzeug
rundeps    :
    - python-click
    - python-itsdangerous
    - python-jinja
    - python-werkzeug
setup      : |
    rm -fr examples/flaskr/
    rm -fr examples/minitwit/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
